#define BUFFER_SIZE 260
#define WINDOWED_ADDRESS 0x4C38B3
#define WINDOW_STYLE_WINDOWED (WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_BORDER | WS_MINIMIZEBOX)
#define WINDOW_STYLE_FULLSCREEN (WS_POPUP | WS_VISIBLE | WS_SYSMENU)
#define COOPERATIVE_LEVEL_WINDOWED DDSCL_NORMAL
#define COOPERATIVE_LEVEL_FULLSCREEN (DDSCL_EXCLUSIVE | DDSCL_FULLSCREEN | DDSCL_ALLOWREBOOT)
//#define GENERAL 1
